module.exports = {
  statdeğişken: [
      { name: "Sistem", type: "açmalı", description: "Otomatik yükseltim ve görevlerdeki otomatik yükseltimi ve çoğu istatistik sistemini devre-dışı bırakır"},
      { name: "tamSesPuan", display: "Full/Tam Puan", type: "puan", description: "Özel belirlenen kategorilerde en yüksek puanı belirleyiniz."},
      { name: "yarımSesPuan",display: "Yarım/Genel Puan", type: "puan", description: "Genel tüm odalarda alacağı veya yarım ses puanı olarak belirleyiniz."},
      { name: "mesajPuan",display: "Mesaj Puanı", type: "puan", description: "Sadece genel sohbet kanalında attığı mesajlardan kazanacağı puanı belirleyiniz."},
      { name: "taglıPuan",display: "Taglı Puanı", type: "puan", description: "Sunucuya getirdiği taglı puanını belirleyiniz."},
      { name: "yetkiliPuan",display: "Yetkili Puanı", type: "puan", description: "Sunucuda yetkiye başlattığı taglı puanını belirleyiniz."},
      { name: "kayıtPuan",display: "Kayıt Puanı", type: "puan", description: "Her kayıtda kazanacağı puanı belirtiniz."},
      { name: "görevPuan",display: "Görev Puanı", type: "puan", description: "Her tamamladığında kazanacağı görev puanını belirleyiniz."},
      { name: "etkinlikPuan", display: "Etkinlik Puanı", type: "puan", category: "stat",  description: "Etkinlik modu açıkken her saniye vereceği puan belirlenir."},
      { name: "izinliKategoriler",  ctype: "ALL", display: "İzinli Kanallar/Kategoriler", type: "kanallar", description: "Yetkili sisteminin çalışacağı tüm kanallar veya kanal belirleyiniz."},
      { name: "fullPuanKategoriler", ctype: "ALL", display: "Full Puanlı  Kanallar/Kategoriler", type: "kanallar", description: "Yetkili sisteminde tam puan alacak kanallar veya kanal belirleyiniz."},
      { name: "ayrıkKanallar",display: "Ayrılan Kanallar", type: "kanallar" , category: "channel",ctype: "VOICE",   description: "Bu istatistik botunda aynı kategoride olup farklı kategorilere ayırmak istediğiniz ses kanallarını seçiniz."},
      { name: "_chats", display: "Sohbet Kategorileri", type: "kategori", description: "Sunucuda bulunan metin kanallarının kategori ayarları"},
      { name: "_voices", display: "Ses Kategorileri", type: "kategori", description: "Sunucuda bulunan metin kanallarının kategori ayarları"},
      { name: "_staffs", display: "Yetkiler", type: "kategori", description: "Sunucuda bulunan metin kanallarının kategori ayarları"},
    ],
  değişkenler: [
      { name: "type", type: "type", display: "Taglı Sistem", category: "guild",  description: "Taglı/Tagsız sistemi aç kapa yapar."},
      { name: "sonYetki", display: "Yükseltim Sistemi Son Yetki", type: "rol", description: "Yetki bilgi komutunda verilecek en son yetkiyi ayarlayınız."},
      { name: "tag", type: "tekil", category: "guild", display: "Taglı Simgesi",  description: "Taglı modda ise buradan tag belirlenir."},
      { name: "tagsiz", type: "tekil", category: "guild", display: "Tagsız Simgesi",  description: "Sunucu içerisinde tagsız olan üyelerin üstünde bulunacak simge veya yazı."},
      { name: "minYaş", type: "tekil" , display: "Minimum Yaş", category: "register",  description: "Sunucuya kayıt olabilecek en düşük yaş."},
      { name: "serverName", type: "tekil" , category: "guild", display: "Sunucu İsmi",  description: "Sunucu ismini buradan belirlenir."},
      { name: "taglıalım", type: "açmalı" , category: "guild", display: "Taglı Alım",  description: "Taglı-Alım modunu aç kapa yapar."},
      { name: "zorunluTeyit", type: "açmalı", category: "guild"},
      { name: "canvasSistem", type: "açmalı", category:"guild"},
      { name: "ekonomiSistem", type: "açmalı", category: "guild"},
      { name: "isimYaş", type: "açmalı", category: "guild", display: "yarram aqqqqqqqqaqqqqq"},
      { name: "küfürEngel", type: "açmalı" , category: "guild", display: "Küfür Engelleme",  description: "Küfür engelleme modunu aç kapa yapar."},
      { name: "reklamEngel", type: "açmalı" , category: "guild", display: "Reklam Engelleme",  description: "Reklam engelleme modunu aç kapa yapar."},
      { name: "spamEngel", type: "açmalı" , category: "guild", display: "Flood Engelleme",  description: "Flood engelleme modunu aç kapa yapar."},
      { name: "capsEngel", type: "açmalı" , category: "guild", display: "Caps-Lock Engelleme",  description: "Caps-Lock engelleme modunu aç kapa yapar."},
      { name: "chatİltifat", type: "açmalı" , category: "guild", display: "Sohbet İltifat",  description: "Sunucuda bulunan tüm sohbet kanallarında belli süre sonra mesaj atan bir kullanıcıya iltifat eder."},
      { name: "chatİzinliler", type : "kanallar", category: "guild", ctype: "ALL", display: "Sohbet İzinliler",   description: "Belirlenen sohbetlerde flood, küfür, caps ve spamı göz ardı eder."},
      { name: "sayılıEmoji", type : "açmalı", category: "guild", ctype: "ALL", display: "Sayılara Emoji",   description: "Bu ayar açıldığında hoş geldin/istatistik gibi işlemlerde sayı yerine sayıyı belirten emoji belirir."},
      { name: "otomatikTaşıma", type: "açmalı", category: "guild", display: "Kayıt Sonrası Otomatik Taşıma", description: "Bu ayar açıldığından kayıt işlemi tamamlandıktan sonra otomatik olarak sohbet odalarına 5 saniye sonra taşıyacaktır"},
      { name: "otomatikSleep", type: "açmalı", category: "guild", display: "Otomatik AFK Odası Taşıma", description: "Bu ayar açıldığından 10 dakika boyunca kulaklığı veya mikrofonu kapalı olan üyeleri otomatik olarak AFK odasına taşır."},
      { name: "Numaralar", type: "tekil", category: "guild", display: "Taglı Simgesi",  description: "Taglı modda ise buradan tag belirlenir."},
      { name: "kayıtsızLimit", type: "tekil", category: "limit", display: "Kayıtsız Atma Limiti",  description: "Kayıtsız yetkisine sahip yetkilinin belirli süre kayıtsız limitini belirler."},
      { name: "muteLimit", type: "tekil", category: "limit",  display: "Mute Atma Limiti",  description: "Mute yetkisine sahip yetkilinin belirli süre Mute limitini belirler."},
      { name: "voiceMuteLimit", type: "tekil", category: "limit",  display: "Ses Mute Atma Limiti",  description: "Mute yetkisine sahip yetkilinin belirli süre Mute limitini belirler."},
      { name: "jailLimit", type: "tekil", category: "limit",  display: "Jail Atma Limiti",  description: "Jail yetkisine sahip yetkilinin belirli süre Jail limitini belirler."},
      { name: "banLimit", type: "tekil", category: "limit",  display: "Ban/Underworld Atma Limiti",  description: "Ban(Underworld) yetkisine sahip yetkilinin belirli süre Ban(Underworld) limitini belirler."},
      { name: "kayıtsızRolleri", type: "roller" , category: "register",  display: "Kayıtsız Rolleri", description: "Sunucuya girdiğinde üzerine verilecek rol(ler)"},
      { name: "erkekRolleri", type: "roller", category: "register" , display: "Erkek Rolleri",  description: "Sunucuya erkek olarak kayıt olduğunda alıcağı rol(ler)"},
      { name: "kadınRolleri", type: "roller" , category: "register", display: "Kadın Rolleri",  description: "Sunucuya kadın olarak kayıt olduğunda alıcağı rol(ler)"},
      { name: "teyitciRolleri", type: "roller" , category: "register", display: "Teyitci Rolleri",  description: "Sunucuda kayıt yetkisine sahip olacak rol(ler)"},
      { name: "tagRolü", type: "rol" , category: "register", display: "Tag Rolü",  description: "Taglı sistem açık ise bir üye tag aldığında verilecek rol."},
      { name: "boosterRolü", type: "rol" , category: "guild", display: "Booster Rolü",  description: "Sunucu üzerinde bulunan Takviye yetkilerine ve ayrıcalıklarına sahip olacak rol."},
      { name: "vipRolü", type: "rol" , category: "role", display: "Özel (VIP) Üye Rolü",  description: "Sunucu taglı-alım dahi olsa kayıtsıza düşmeyecek ve özel üyelere verilecek rol."},
      { name: "kurucuRolleri", display: "Kurucu Rolleri", type: "roller" , category: "role",  description: "Sunucu üzerinde kurucu olarak belirlenen rol(ler)"},
      { name: "altYönetimRolleri", display: "Alt Yönetim Rolleri", type: "roller" , category: "role",  description: "Sunucu üzerinde alt yönetim olarak belirlenen rol(ler)"},
      { name: "yönetimRolleri", display: "Orta Yönetim Rolleri", type: "roller" , category: "role",  description: "Sunucu üzerinde yönetim olarak belirlenen rol(ler)"},
      { name: "üstYönetimRolleri", display: "Üst Yönetim Rolleri", type: "roller" , category: "role",  description: "Sunucu üzerinde üst yönetim olarak belirlenen rol(ler)"},
      { name: "underworldRolü", display: "Underworld Rolü", type: "rol" , category: "punitives",  description: "Sunucuda ban yerine kalıcı jail mantığı ile oluşturulan, Underworld sistemine verilecek rol."},
      { name: "banHammer", display: "Underworld Atabilecek Roller", type: "roller" , category: "punitives",  description: "Sunucuda Underworldee gönderecek rol(ler)"},
      { name: "jailHammer", display: "Jail Atabilecek Roller", type: "roller" , category: "punitives",  description: "Sunucuda Jailee gönderecek rol(ler)"},
      { name: "voiceMuteHammer", display: "Ses Mute Atabilecek Roller", type: "roller" , category: "punitives",  description: "Sunucuda ses mutesi atabilecek rol(ler)"},
      { name: "muteHammer", display: "Mute Atabilecek Roller", type: "roller" , category: "punitives",  description: "Sunucuda mute atabilecek rol(ler)"},
      { name: "warnHammer", display: "Uyarı Atabilecek Roller", type: "roller" , category: "punitives",  description: "Sunucuda uyarı verebilecek rol(ler)"},
      { name: "muteRolü", display: "Susturuldu Rolü", type: "rol", category: "punitives" ,  description: "Sunucuda metin kanallarında susturulduğunda verilecek rol"},
      { name: "cezalıRolü", display: "Cezalı Rolü", type: "rol" , category: "punitives",  description: "Sunucuda jail atılınca verilecek rol"},
      { name: "şüpheliRolü", display: "Şüpheli Rolü", type: "rol", category: "punitives" ,  description: "Sunucuda 7 gün veya daha önce açılmış hesaplara verilecek rol"},
      { name: "yasaklıTagRolü", display: "Yasaklı Tag Rolü", type: "rol" , category: "punitives",  description: "Sunucuda yasaklı tag mevcut ise üstünde bulunan üyelere verilcek rol"},
      { name: "Katıldı", display: "Toplantı (Katıldı) Rolü", type: "rol" , category: "guild",  description: "Sunucuda toplantı sonu katılan üyelerin üzerine verilecek rol"},
      { name: "Yetkiler", display: "Sağda Gözüken Yetki Rolleri", type: "roller" , category: "role",  description: "Sunucuda bulunan Sağda görüken yetki rol(ler)"},
      { name: "sorunCozmeKategorisi", display: "Sorun Çözme Kategorisi", type: "kanal" , category: "guild",ctype: "CATEGORY",   description: "Sunucuda sorun çözme mevcut ise kategorisini seçin."},
      { name: "özelOdaKategorisi", type: "kanal", category: "guild"},
      { name: "sorunÇözmeciler", display: "Sorun Çözmeci Rolleri", type: "roller" , category: "guild",  description: "Sorun çözmeciler var ise rol(ler)"},
      { name: "yükselticiRoller", display: "Yetki Yükseltici Roller", type: "roller", category: "stat",  description: "Tüm yetki role komut ile yerleştirecek ve limitsiz bi şekilde yerleştirecek rol(ler)"},
      { name: "limitliYükselticiRolleri", display: "Limitli Yetki Yükseltici Roller", type: "roller", category: "stat",  description: "Sadece belirli role kadar yükseltebilecek limitli rol(ler)"},
      { name: "yükseltimSınırı", display: "Yetki Yükseltim Limiti", type: "tekil", category: "stat",  description: "Belirli roller burada index numarasını girin."},
      { name: "etkinlikKatılımcısı", display: "Etkinlik Katılımcısı Rolü", type: "rol" , category: "guild",  description: "Eğer ki otomatik sistem üzerinden kurulum yapmıyorsanız buradan etkinlik katılımcısını seçin."},
      { name: "cekilisKatılımcısı", display: "Çekiliş Katılımcısı Rolü", type: "rol" , category: "guild",  description: "Eğer ki otomatik sistem üzerinden kurulum yapmıyorsanız buradan çekiliş katılımcısını seçin."},
      { name: "TerfiLog", display: "Yetki Yükseltim Log Kanalı", type: "kanal" , category: "channel",ctype: "TEXT",   description: "Bir yetkili otomatik şekilde yetki atladığında kayıt atacağı kanal."},
      { name: "ilkYetki", display: [], type: "rol", category: "guild", description: []},
      { name: "botKomutRolü", display: [],type: "rol", category: "guild", description: []},
      { name: "verilecekRoller", display: [], type: "roller", category: "guild"},
      {name: "fullPuanKategoriler", display : [], type: "kanal", category: "guild", ctype: "CATEGORY", description: []},
      { name: "izinliKanallar", display: "Komut İzinli Kanallar", type: "kanallar" , category: "channel",ctype: "TEXT",   description: "Bot komutlarını sadece bu kanallar üzerinde kullansınlar."},
      { name: "hoşgeldinKanalı", display: "Hoşgeldin Kanalı", type: "kanal" , category: "register",ctype: "TEXT",   description: "Bir üye sunucuya katıldığında otomatik olarak atıcağı kanal"},
      { name: "chatKanalı", display: "Chat Kanalı", type: "kanal" , category: "channel",ctype: "TEXT",   description: "Sunucuda ekonomi oyunlarınını atacağı bir kanal belirlemelisin."},
      { name: "kurallarKanalı", display: "Kurallar Kanalı", type: "kanal" , category: "channel",ctype: "TEXT",   description: "Kurallar kanalınız ismi kurallar değil ise buradan seçim yapabilirsiniz."},
      { name: "toplantıKanalı", display: "Toplantı Kanalı", type: "kanal" , category: "channel",ctype: "VOICE",   description: "Toplantı kanalı seçmek zorunlu değil seçerseniz de sadece o kanalda toplantı gerçekleşir."},
      { name: "etkinlikIzinliler", display: "Etkinlik Kategorileri", type: "kanallar" , category: "channel",ctype: "CATEGORY",   description: "Etkinlik modu açık ise sadece bu kanallarda puan ve ödül ver."},
      { name: "davetKanalı", display: "Davet(Invite) Kanalı", type: "kanal" , category: "channel",ctype: "TEXT",   description: "Biri sunucuya katıldığında kim tarafından davet edildiği kayıt altına alınacak kanal"},
      { name: "publicKategorisi", display: "Public Kategorisi", type: "kanal" , category: "channel", ctype: "CATEGORY",  description: "Sohbet odalarının kategorisini seçiniz."},
      { name: "registerKategorisi", display: "Register Kategorisi", type: "kanal", category: "register" ,ctype: "CATEGORY",  description: "Kayıt odalarının kategorisini seçiniz."},
      { name: "streamerKategorisi", display: "Streamer Kategorisi", type: "kanal" , category: "channel", ctype: "CATEGORY",  description: "Yayın odalarının kategorisiniz seçiniz."},
      { name: "aloneKategorisi", display: "", type: "kanal", category: "channel", ctype: "CATEGORY", description: ""},
      { name: "privateKategorisi", display: "", type : "kanal", category: "channel", ctype: "CATEGORY", description: ""},
      { name: "eğlenceKategorisi", display: "", type : "kanal", category: "channel", ctype: "CATEGORY", description: ""},
      { name: "sıralamaKanalı", display: "", type: "kanal", category: "channel"},
      { name: "musicRooms", display: "Müzik Kanalları", type: "kanallar" , category: "channel", ctype: "VOICE",  description: "Müzik odalarınız var ise belirtiniz yok ise es geçebilirsiniz."},
      { name: "photoChatKanalı", display: "Görsel Chat Kanalı", type: "kanal", category: "channel" , ctype: "TEXT",   description: "Bir kanal belirlerseniz sadece o kanalda resim dışında bir mesaj atılmayacaktır."},
      { name: "sleepRoom", display: "Sleep(AFK) Kanalı", type: "kanal", category: "channel" ,ctype: "VOICE",   description: "Yayın ve sohbet odalarında belirli süre kulaklığı mikrofonu kapalı olan üyeleri otomatik olarak bu kanala taşır."},
      { name: "ilkYetki", display: "Başlangıç Yetki", type: "rol", category: "role",  description: "Yetkili olduğu gibi sağda vericek rol."},
             { name: "haftaBirincileri", display: "Hafta Birincileri Sistemi", type: "açmalı", category: "stat",  description: "Sıralama da haftanın ses/mesaj birincilerine rol vermek ister misin?"},
      { name: "haftaninBirinciRolü", display: "Hafta Birincileri Rolü", type: "rol", category: "stat",  description: "Haftanın birincilerine verilecek rol."},
         { name: "mazeretliRolü", display: "Mazeretli Rolü", type: "rol", category:"guild",  description: "Sunucuda toplantıya mazereti olanlara verilecek rol."},
      { name: "mazeretSorumlusu", display: "Mazeret Sorumlusu", type: "roller", category:"guild",  description: "Mazeretli rolü verecek sorumlular rol(ler)"},
      { name: "dcCezalıRolü", display: "DC Cezalı Rolü", type: "rol", category:"punitives",  description: "Doğruluk mu? Cesaretlik mi? oyunununa katılmayacak rol"},
      { name: "dcSorumlusu", display: "DC Sorumlusu", type: "roller", category:"guild",  description: "Doğruluk mu? Cesaretlik mi? oyununun sorumluları rol(ler)"},
      { name: "vkCezalıRolü", display: "VK Cezalı Rolü", type: "rol", category:"punitives",  description: "Vampir Köylü oyunununa katılmayacak rol"},
      { name: "vkSorumlusu", display: "VK Sorumlusu", type: "roller", category:"guild",  description: "Vampir Köylü oyunun sorumluları rol(ler)"},
      { name: "streamerCezalıRolü", display: "Streamer Cezalı Rolü", type: "rol", category:"punitives",  description: "Yayın odalarına katılamayacak rol(ler)"},
      { name: "streamerSorumlusu", display: "Streamer Sorumlusu", type: "roller",category: "guild",  description: "Yayın odalarının sorumluları rol(ler)"},
      { name: "etkinlikCezalıRolü", display: "Etkinlik Cezalı Rolü", type: "rol", category:"punitives",  description: "Etkinliklere katılamayacak rol"},
      { name: "etkinlikSorumlusu", display: "Etkinlik Sorumlusu", type: "roller",category: "guild",  description: "Etkinlik sorumluları rol(ler)"},
            { name: "sorumlulukLog", display: "Liderlik / Sorumluluk Puan Bilgi Kanalı", type: "kanal", category: "channel", description: "Eğer ki site üzerinde lider veya sorumluluk rolleri girildiyse belirtilen kanala otomatik puanlama bilgileri atılır."},
        ]
}